import { Skeleton, Typography } from "@mui/material";

import { KPICard } from "@/components/kpi-card";

import { KPI } from "@/services/dashboard/ai-performance/KPIs";

export const ReportsGeneratedByAI: React.FunctionComponent<{ data?: Pick<KPI, 'reportsGeneratedByAI'> }> = ({
  data
}) => {
  return (
    <KPICard title="Reports Generated by AI">
      {data ? (
        <Typography variant="h4" sx={{ fontWeight: 800, color: '#1f6feb', lineHeight: 1.1 }}>
          {data.reportsGeneratedByAI}
        </Typography>
      ) : (
        <Skeleton variant="text" animation="wave" />
      )}
    </KPICard>
  );
}
