import { KPIProps } from "@/services/dashboard/ai-performance/KPIs";
import { Stack, Typography } from "@mui/material";

import { KPICard } from "../components/kpi-card";

export const ReportsGeneratedByAI: React.FunctionComponent<{ data: Pick<KPIProps, 'reportsGeneratedByAI'> }> = ({
  data
}) => {
  return (
    <KPICard>
      <Stack direction="row" alignItems="center" spacing={0.75}>
        <Typography variant="body2" color="text.secondary">
          Reports Generated by AI
        </Typography>
      </Stack>
      <Typography variant="h4" sx={{ fontWeight: 800, color: '#1f6feb', lineHeight: 1.1 }}>
        {data.reportsGeneratedByAI}
      </Typography>
    </KPICard>
  );
}
