import { Card, CardContent, Stack, Typography } from "@mui/material";

export default function ReportsGeneratedByAI() {
  return (
    <Card elevation={0} sx={{ borderRadius: 3, height: '100%' }}>
      <CardContent sx={{ py: 2.25, px: 2.5 }}>
        <Stack spacing={1.25}>
          <Stack direction="row" alignItems="center" spacing={0.75}>
            <Typography variant="body2" color="text.secondary">
              Reports Generated by AI
            </Typography>
          </Stack>
          <Typography variant="h4" sx={{ fontWeight: 800, color: '#1f6feb', lineHeight: 1.1 }}>
            1,250
          </Typography>
        </Stack>
      </CardContent>
    </Card>
  );
}
